version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: poller
      POSTGRES_USER: poller
      POSTGRES_DB: poller
    ports:
    - 5432:5432
    volumes:
    - c:\docker-volumes\poller-sql:/var/lib/postgresql/data

  server:
    depends_on:
    - db
    build: ./server
    restart: always
    environment: 
      PORT: 3030
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db
      TYPEORM_USERNAME: poller
      TYPEORM_PASSWORD: poller
      TYPEORM_DATABASE: poller
      TYPEORM_PORT: 5432
      TYPEORM_SYNCHRONIZE: 'true'
      TYPEORM_LOGGING: 'true'
      TYPEORM_CHACE: true,
      TYPEORM_ENTITIES: build/entity/**/*.js
      TYPEORM_MIGRATIONS: build/migration/**/*.js
    ports:
    - 3030:3030
